- name: configuring cart
  hosts: cart
  become: yes
  
  tasks:
  - name: nodejs:20 module enabling
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: installing nodejs 
    ansible.builtin.dnf: 
      name: nodejs
      state: present

  - name: creating roboshop system user
    ansible.builtin.cart: 
      name: roboshop
      system: yes
      home: /app
      shell: /sbin/nologin
      comment: roboshop system user

  - name: deleting application directory
    ansible.builtin.file: 
      path: /app
      state: absent

  - name: creating application directory
    ansible.builtin.file: 
      path: /app
      state: directory

  - name: deleting cart.zip
    ansible.builtin.file: 
      path: /tmp/cart.zip
      state: absent

  - name: downloading cart
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
      dest: /tmp/cart.zip

  - name: unarchive the cart
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes

  - name: installing package dependencies
    community.general.npm: 
      path: /app

  - name: copy the systemd cart service
    ansible.builtin.copy: 
      src: cart.service
      dest: /etc/systemd/system/cart.service

  - name: reloading the daemon
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: start and enable the cart
    ansible.builtin.service:
      name: cart
      enabled: yes
      state: restarted
