- name: configuring frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: enabling nginx 1.24 module
    ansible.builtin.command: dnf module enable nginx:1.24 -y 
    
  - name: installing nginx serivice
    ansible.builtin.dnf: 
      name: nginx
      state: present

  - name: enable and start nginx serivice
    ansible.builtin.service:
      name: nginx
      enabled: yes
      start: started

  - name: remove the default content of nginx html page
    ansible.builtin.file:
      name: absent
      path: /usr/share/nginx/html

  - name: create nginx html directory
    ansible.builtin.file:
      state: present
      path: /usr/share/nginx/html

  - name: download the frontend content
    ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

  - name: unzip the frontend.zip directory
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: remove the default nginx config file
    ansible.builtin.file:
      state: absent
      path: /etc/nginx/nginx.conf

  - name: copy the nginx.conf file
    ansible.builtin.template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf

  - name: restart nginx
    ansible.builtin.serivice:
      name: nginx
      state: restarted