[mongodb]
mongodb-dev.sukr.store

[catalogue]
catalogue-dev.sukr.store

[user]
user-dev.sukr.store

[all:vars]
ec2_username=ec2_username
ec2_password=DevOps321
MONGODB_HOST=mongodb-dev.sukr.store
REDIS_HOST=redis-dev.sukr.store
CATALOGUE_HOST=catalogue-dev.sukr.store
