[mongodb]
mongodb-dev.sukr.store

[catalogue]
catalogue-dev.sukr.store

[user]
user-dev.sukr.store

[redis]
redis-dev.sukr.store

[mysql]
mysql-dev.sukr.store

[all:vars]
ec2_username=ec2_username
ec2_password=DevOps321
MONGODB_HOST=mongodb-dev.sukr.store
REDIS_HOST=redis-dev.sukr.store
CATALOGUE_HOST=catalogue-dev.sukr.store
CART_HOST=cart-dev.sukr.store
USER_HOST=user-dev.sukr.store
MYSQL_HOST=mysql-dev.sukr.store